# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interface.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\"/\n\x0eMapSizeRequest\x12\r\n\x05width\x18\x01 \x02(\x05\x12\x0e\n\x06height\x18\x02 \x02(\x05\"\x1f\n\x0cMapSizeReply\x12\x0f\n\x07message\x18\x01 \x02(\t\"+\n\x15SecondForTimerRequest\x12\x12\n\ntimeSecond\x18\x01 \x02(\x05\"&\n\x13SecondForTimerReply\x12\x0f\n\x07message\x18\x01 \x02(\t\"$\n\x0fNbplayerRequest\x12\x11\n\tnbPlayers\x18\x01 \x02(\x05\" \n\rNbplayerReply\x12\x0f\n\x07message\x18\x01 \x02(\t\"&\n\x10StartGameRequest\x12\x12\n\nisStarting\x18\x01 \x02(\x05\"!\n\x0eStartGameReply\x12\x0f\n\x07message\x18\x01 \x02(\t\"<\n\x12InscriptionRequest\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02ip\x18\x02 \x02(\t\x12\x0c\n\x04role\x18\x03 \x02(\t\"#\n\x10InscriptionReply\x12\x0f\n\x07message\x18\x01 \x02(\t\",\n\x0bMoveRequest\x12\n\n\x02ip\x18\x01 \x02(\t\x12\x11\n\tdirection\x18\x02 \x02(\t\"\x1c\n\tMoveReply\x12\x0f\n\x07message\x18\x01 \x02(\t2\xc1\x02\n\x0eLoupdorService\x12-\n\tCreateMap\x12\x0f.MapSizeRequest\x1a\r.MapSizeReply\"\x00\x12>\n\x0cTimerForTour\x12\x16.SecondForTimerRequest\x1a\x14.SecondForTimerReply\"\x00\x12\x31\n\x0bNbMaxPlayer\x12\x10.NbplayerRequest\x1a\x0e.NbplayerReply\"\x00\x12\x31\n\tStartGame\x12\x11.StartGameRequest\x1a\x0f.StartGameReply\"\x00\x12\x36\n\nInscrption\x12\x13.InscriptionRequest\x1a\x11.InscriptionReply\"\x00\x12\"\n\x04Move\x12\x0c.MoveRequest\x1a\n.MoveReply\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPSIZEREQUEST']._serialized_start=19
  _globals['_MAPSIZEREQUEST']._serialized_end=66
  _globals['_MAPSIZEREPLY']._serialized_start=68
  _globals['_MAPSIZEREPLY']._serialized_end=99
  _globals['_SECONDFORTIMERREQUEST']._serialized_start=101
  _globals['_SECONDFORTIMERREQUEST']._serialized_end=144
  _globals['_SECONDFORTIMERREPLY']._serialized_start=146
  _globals['_SECONDFORTIMERREPLY']._serialized_end=184
  _globals['_NBPLAYERREQUEST']._serialized_start=186
  _globals['_NBPLAYERREQUEST']._serialized_end=222
  _globals['_NBPLAYERREPLY']._serialized_start=224
  _globals['_NBPLAYERREPLY']._serialized_end=256
  _globals['_STARTGAMEREQUEST']._serialized_start=258
  _globals['_STARTGAMEREQUEST']._serialized_end=296
  _globals['_STARTGAMEREPLY']._serialized_start=298
  _globals['_STARTGAMEREPLY']._serialized_end=331
  _globals['_INSCRIPTIONREQUEST']._serialized_start=333
  _globals['_INSCRIPTIONREQUEST']._serialized_end=393
  _globals['_INSCRIPTIONREPLY']._serialized_start=395
  _globals['_INSCRIPTIONREPLY']._serialized_end=430
  _globals['_MOVEREQUEST']._serialized_start=432
  _globals['_MOVEREQUEST']._serialized_end=476
  _globals['_MOVEREPLY']._serialized_start=478
  _globals['_MOVEREPLY']._serialized_end=506
  _globals['_LOUPDORSERVICE']._serialized_start=509
  _globals['_LOUPDORSERVICE']._serialized_end=830
# @@protoc_insertion_point(module_scope)
